version "4.5.0"

#include "zscript/BetterStrifeGutamatics/Include.zsc"
#include "zscript/BetterStrife/BetterStrifeLevelPostProcessor/BetterStrifeLevelPostProcessor.zc"
#include "zscript/BetterStrife/BetterStrifeMarkerProjectionHandler/BetterStrifeMarkerProjectionHandler.zc"
#include "zscript/BetterStrife/BetterStrifeHandler/BetterStrifeHandler.zc"
#include "zscript/BetterStrife/BetterStrifeExitMarker/BetterStrifeExitMarker.zc"
