version "4.8.2"

// Copyright 2021 - 2024 Nash Muhandes
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Core
#include "zscript/BetterStrifeGutamatics/Include.zsc"
#include "zscript/BetterStrife/BetterStrifeHandler.zc"

// Level post processor
#include "zscript/BetterStrife/level/BetterStrifeLevelPostProcessor.zc"

// Actor plugins
#include "zscript/BetterStrife/player/BetterStrifePlayerPlugin.zc"
#include "zscript/BetterStrife/npc/BetterStrifeOraclePlugin.zc"

// Quest
#include "zscript/BetterStrife/quest/BetterStrifeQuest.zc"
#include "zscript/BetterStrife/quest/BetterStrifeQuestHandler.zc"
#include "zscript/BetterStrife/quest/BetterStrifeQuestMarker.zc"
#include "zscript/BetterStrife/level/StrifeQuestMarkers.zc"
#include "zscript/BetterStrife/level/SVEQuestMarkers.zc"

// World actors
#include "zscript/BetterStrife/misc/BetterStrifeMeat.zc"
#include "zscript/BetterStrife/misc/BetterStrifeGlassJunk.zc"

// NPCs
#include "zscript/BetterStrife/npc/BetterStrifePrisonMerchant.zc"

// Exit markers
#include "zscript/BetterStrife/quest/BetterStrifeExitMarker.zc"

// Inventory
#include "zscript/BetterStrife/player/BetterStrifePlayerFlashlight.zc"

// Weapons
//#include "zscript/BetterStrife/weapons/BetterStrifeWeapons.zc"

// HUD and UI
#include "zscript/BetterStrife/quest/BetterStrifeMarkerProjectionHandler.zc"
//#include "zscript/BetterStrife/UI/HUD/BetterStrifeStatusBar.zc"

// Options menu
#include "zscript/BetterStrife/UI/OptionMenu/BetterStrifeOptionMenu.zc"
